server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true